const countries = [
  "Afghanistan 🇦🇫",
  "Algeria 🇩🇿",
  "Angola 🇦🇴",
  "Bangladesh 🇧🇩",
  "Bolivia 🇧🇴",
  "Cambodia 🇰🇭",
  "Chad 🇹🇩",
  "Congo 🇨🇩",
  "Cuba 🇨🇺",
  "Dominican Republic 🇩🇴",
  "Egypt 🇪🇬",
  "Ethiopia 🇪🇹",
  "Ghana 🇬🇭",
  "Guatemala 🇬🇹",
  "India 🇮🇳",
  "Indonesia 🇮🇩",
  "Iraq 🇮🇶",
  "Kenya 🇰🇪",
  "Libya 🇱🇾",
  "Mali 🇲🇱",
  "Mozambique 🇲🇿",
  "Nicaragua 🇳🇮",
  "Pakistan 🇵🇰",
  "Peru 🇵🇪",
  "Somalia 🇸🇴",
  "Sudan 🇸🇩",
  "Syria 🇸🇾",
  "Tanzania 🇹🇿",
  "Vietnam 🇻🇳",
  "Yemen 🇾🇪"
];export default countries;

